name: barberia_cliente
description: BarberDesk Cliente — App para clientes de barberías
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
